TEMPLATE = app
DESTDIR = dist
TARGET = QtRstaPlot
CONFIG += console
QT = core gui widgets opengl
SOURCES += ClRsta.cpp MainForm.cpp QRstaWidget.cpp main.cpp
HEADERS += ClRsta.h MainForm.h QRstaWidget.h
FORMS += MainForm.ui
RESOURCES += 
OBJECTS_DIR = build
MOC_DIR = build
RCC_DIR = build
UI_DIR = build
LIBS += -lOpenCL